/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scales/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Scales */
        get: operations["read_scales"];
        put?: never;
        /** Create Scale */
        post: operations["create_scale"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scales/{scale_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Scale */
        get: operations["read_scale"];
        put?: never;
        post?: never;
        /** Delete Grade Equivalence */
        delete: operations["delete_scale"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scales/{scale_id}/equivalences/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Equivalence For Scale */
        post: operations["create_equivalence_for_scale"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scales/{scale_id}/equivalences/{equivalence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Grade Equivalence */
        delete: operations["delete_equivalence_for_scale"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfer/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert Grade */
        post: operations["convert_grade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcademicScaleCreate */
        AcademicScaleCreate: {
            /** Country Name */
            country_name: string;
            /** Scale Description */
            scale_description: string;
            /** Total Grades */
            total_grades?: number | null;
        };
        /** AcademicScaleRead */
        AcademicScaleRead: {
            /** Country Name */
            country_name: string;
            /** Scale Description */
            scale_description: string;
            /** Total Grades */
            total_grades?: number | null;
            /** Id */
            id: number;
            /** Equivalences */
            equivalences?: components["schemas"]["GradeEquivalenceRead"][];
        };
        /** GradeEquivalenceCreate */
        GradeEquivalenceCreate: {
            /**
             * Origin Grade
             * @description Grade from origin country
             */
            origin_grade: string;
            /** Spanish 5 10 */
            spanish_5_10: number | string;
            /** Spanish 1 4 */
            spanish_1_4?: number | null;
            spanish_literal: components["schemas"]["SpanishLiteralEnum"];
        };
        /** GradeEquivalenceRead */
        GradeEquivalenceRead: {
            /**
             * Origin Grade
             * @description Grade from origin country
             */
            origin_grade: string;
            /** Spanish 5 10 */
            spanish_5_10: string;
            /** Spanish 1 4 */
            spanish_1_4?: number | null;
            spanish_literal: components["schemas"]["SpanishLiteralEnum"];
            /** Id */
            id: number;
            /** Scale Id */
            scale_id: number;
        };
        /**
         * GradeInput
         * @description Schema for the grade to be converted
         */
        GradeInput: {
            /** Subject */
            subject?: string | null;
            /** Origin Grade */
            origin_grade: string;
        };
        /**
         * GradeOutput
         * @description Schema for the converted grade
         */
        GradeOutput: {
            /** Subject */
            subject?: string | null;
            /** Origin Grade */
            origin_grade: string;
            /** Converted 5 10 */
            converted_5_10: string;
            /** Converted Literal */
            converted_literal: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SpanishLiteralEnum
         * @enum {string}
         */
        SpanishLiteralEnum: "APROBADO" | "NOTABLE" | "SOBRESALIENTE" | "MATRICULA";
        /**
         * TransferFormat
         * @enum {string}
         */
        TransferFormat: "json" | "csv" | "xlsx" | "ods" | "json-file";
        /**
         * TransferRequest
         * @description Schema for the transfer request
         */
        TransferRequest: {
            /** Scale Id */
            scale_id: number;
            /** Grades */
            grades: components["schemas"]["GradeInput"][];
        };
        /**
         * TransferResponse
         * @description The clean data sent back
         */
        TransferResponse: {
            /** Conversion */
            conversion: components["schemas"]["GradeOutput"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_scales: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicScaleRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scale: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcademicScaleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicScaleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_scale: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scale_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicScaleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scale: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scale_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_equivalence_for_scale: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scale_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeEquivalenceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeEquivalenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_equivalence_for_scale: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scale_id: number;
                equivalence_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    convert_grade: {
        parameters: {
            query?: {
                /** @description Response format for converted grades */
                format?: components["schemas"]["TransferFormat"];
                /** @description Optional filename for file responses */
                filename?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
