// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ConvertGradeData, ConvertGradeErrors, ConvertGradeResponses, CreateEquivalenceForScaleData, CreateEquivalenceForScaleErrors, CreateEquivalenceForScaleResponses, CreateScaleData, CreateScaleErrors, CreateScaleResponses, ReadScaleData, ReadScaleErrors, ReadScaleResponses, ReadScalesData, ReadScalesErrors, ReadScalesResponses, RootGetData, RootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Scales
 */
export const readScales = <ThrowOnError extends boolean = false>(options?: Options<ReadScalesData, ThrowOnError>) => (options?.client ?? client).get<ReadScalesResponses, ReadScalesErrors, ThrowOnError>({ url: '/scales/', ...options });

/**
 * Create Scale
 */
export const createScale = <ThrowOnError extends boolean = false>(options: Options<CreateScaleData, ThrowOnError>) => (options.client ?? client).post<CreateScaleResponses, CreateScaleErrors, ThrowOnError>({
    url: '/scales/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Scale
 */
export const readScale = <ThrowOnError extends boolean = false>(options: Options<ReadScaleData, ThrowOnError>) => (options.client ?? client).get<ReadScaleResponses, ReadScaleErrors, ThrowOnError>({ url: '/scales/{scale_id}', ...options });

/**
 * Create Equivalence For Scale
 */
export const createEquivalenceForScale = <ThrowOnError extends boolean = false>(options: Options<CreateEquivalenceForScaleData, ThrowOnError>) => (options.client ?? client).post<CreateEquivalenceForScaleResponses, CreateEquivalenceForScaleErrors, ThrowOnError>({
    url: '/scales/{scale_id}/equivalences/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Convert Grade
 */
export const convertGrade = <ThrowOnError extends boolean = false>(options: Options<ConvertGradeData, ThrowOnError>) => (options.client ?? client).post<ConvertGradeResponses, ConvertGradeErrors, ThrowOnError>({
    url: '/transfer/convert',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });
