// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AcademicScaleCreate
 */
export type AcademicScaleCreate = {
    /**
     * Country Name
     */
    country_name: string;
    /**
     * Scale Description
     */
    scale_description: string;
    /**
     * Total Grades
     */
    total_grades?: number | null;
};

/**
 * AcademicScaleRead
 */
export type AcademicScaleRead = {
    /**
     * Country Name
     */
    country_name: string;
    /**
     * Scale Description
     */
    scale_description: string;
    /**
     * Total Grades
     */
    total_grades?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Equivalences
     */
    equivalences?: Array<GradeEquivalenceRead>;
};

/**
 * GradeEquivalenceCreate
 */
export type GradeEquivalenceCreate = {
    /**
     * Origin Grade
     *
     * Grade from origin country
     */
    origin_grade: string;
    /**
     * Spanish 5 10
     */
    spanish_5_10: number | string;
    /**
     * Spanish 1 4
     */
    spanish_1_4?: number | null;
    spanish_literal: SpanishLiteralEnum;
};

/**
 * GradeEquivalenceRead
 */
export type GradeEquivalenceRead = {
    /**
     * Origin Grade
     *
     * Grade from origin country
     */
    origin_grade: string;
    /**
     * Spanish 5 10
     */
    spanish_5_10: string;
    /**
     * Spanish 1 4
     */
    spanish_1_4?: number | null;
    spanish_literal: SpanishLiteralEnum;
    /**
     * Id
     */
    id: number;
    /**
     * Scale Id
     */
    scale_id: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SpanishLiteralEnum
 */
export type SpanishLiteralEnum = 'APROBADO' | 'NOTABLE' | 'SOBRESALIENTE' | 'MATRICULA';

/**
 * TransferRequest
 *
 * Schema for the Activepieces automation request
 */
export type TransferRequest = {
    /**
     * Scale Id
     */
    scale_id: number;
    /**
     * Origin Grade
     */
    origin_grade: string;
};

/**
 * TransferResponse
 *
 * The clean data sent back to the automation flow
 */
export type TransferResponse = {
    /**
     * Original
     */
    original: string;
    /**
     * Converted 5 10
     */
    converted_5_10: string;
    /**
     * Converted Literal
     */
    converted_literal: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadScalesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/scales/';
};

export type ReadScalesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadScalesError = ReadScalesErrors[keyof ReadScalesErrors];

export type ReadScalesResponses = {
    /**
     * Response Read Scales
     *
     * Successful Response
     */
    200: Array<AcademicScaleRead>;
};

export type ReadScalesResponse = ReadScalesResponses[keyof ReadScalesResponses];

export type CreateScaleData = {
    body: AcademicScaleCreate;
    path?: never;
    query?: never;
    url: '/scales/';
};

export type CreateScaleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScaleError = CreateScaleErrors[keyof CreateScaleErrors];

export type CreateScaleResponses = {
    /**
     * Successful Response
     */
    200: AcademicScaleRead;
};

export type CreateScaleResponse = CreateScaleResponses[keyof CreateScaleResponses];

export type ReadScaleData = {
    body?: never;
    path: {
        /**
         * Scale Id
         */
        scale_id: number;
    };
    query?: never;
    url: '/scales/{scale_id}';
};

export type ReadScaleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadScaleError = ReadScaleErrors[keyof ReadScaleErrors];

export type ReadScaleResponses = {
    /**
     * Successful Response
     */
    200: AcademicScaleRead;
};

export type ReadScaleResponse = ReadScaleResponses[keyof ReadScaleResponses];

export type CreateEquivalenceForScaleData = {
    body: GradeEquivalenceCreate;
    path: {
        /**
         * Scale Id
         */
        scale_id: number;
    };
    query?: never;
    url: '/scales/{scale_id}/equivalences/';
};

export type CreateEquivalenceForScaleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEquivalenceForScaleError = CreateEquivalenceForScaleErrors[keyof CreateEquivalenceForScaleErrors];

export type CreateEquivalenceForScaleResponses = {
    /**
     * Successful Response
     */
    200: GradeEquivalenceRead;
};

export type CreateEquivalenceForScaleResponse = CreateEquivalenceForScaleResponses[keyof CreateEquivalenceForScaleResponses];

export type ConvertGradeData = {
    body: TransferRequest;
    path?: never;
    query?: never;
    url: '/transfer/convert';
};

export type ConvertGradeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConvertGradeError = ConvertGradeErrors[keyof ConvertGradeErrors];

export type ConvertGradeResponses = {
    /**
     * Successful Response
     */
    200: TransferResponse;
};

export type ConvertGradeResponse = ConvertGradeResponses[keyof ConvertGradeResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
