// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ConvertGradeTransferConvertPostData, ConvertGradeTransferConvertPostErrors, ConvertGradeTransferConvertPostResponses, CreateEquivalenceForScaleScalesScaleIdEquivalencesPostData, CreateEquivalenceForScaleScalesScaleIdEquivalencesPostErrors, CreateEquivalenceForScaleScalesScaleIdEquivalencesPostResponses, CreateScaleScalesPostData, CreateScaleScalesPostErrors, CreateScaleScalesPostResponses, ReadScaleScalesScaleIdGetData, ReadScaleScalesScaleIdGetErrors, ReadScaleScalesScaleIdGetResponses, ReadScalesScalesGetData, ReadScalesScalesGetErrors, ReadScalesScalesGetResponses, RootGetData, RootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Scales
 */
export const readScalesScalesGet = <ThrowOnError extends boolean = false>(options?: Options<ReadScalesScalesGetData, ThrowOnError>) => (options?.client ?? client).get<ReadScalesScalesGetResponses, ReadScalesScalesGetErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/scales/',
    ...options
});

/**
 * Create Scale
 */
export const createScaleScalesPost = <ThrowOnError extends boolean = false>(options: Options<CreateScaleScalesPostData, ThrowOnError>) => (options.client ?? client).post<CreateScaleScalesPostResponses, CreateScaleScalesPostErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/scales/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Scale
 */
export const readScaleScalesScaleIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadScaleScalesScaleIdGetData, ThrowOnError>) => (options.client ?? client).get<ReadScaleScalesScaleIdGetResponses, ReadScaleScalesScaleIdGetErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/scales/{scale_id}',
    ...options
});

/**
 * Create Equivalence For Scale
 */
export const createEquivalenceForScaleScalesScaleIdEquivalencesPost = <ThrowOnError extends boolean = false>(options: Options<CreateEquivalenceForScaleScalesScaleIdEquivalencesPostData, ThrowOnError>) => (options.client ?? client).post<CreateEquivalenceForScaleScalesScaleIdEquivalencesPostResponses, CreateEquivalenceForScaleScalesScaleIdEquivalencesPostErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/scales/{scale_id}/equivalences/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Convert Grade
 */
export const convertGradeTransferConvertPost = <ThrowOnError extends boolean = false>(options: Options<ConvertGradeTransferConvertPostData, ThrowOnError>) => (options.client ?? client).post<ConvertGradeTransferConvertPostResponses, ConvertGradeTransferConvertPostErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/transfer/convert',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });
