// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://.openapi.json` | (string & {});
};

/**
 * AcademicScaleCreate
 */
export type AcademicScaleCreate = {
    /**
     * Country Name
     */
    country_name: string;
    /**
     * Scale Description
     */
    scale_description: string;
    /**
     * Total Grades
     */
    total_grades?: number | null;
};

/**
 * AcademicScaleRead
 */
export type AcademicScaleRead = {
    /**
     * Country Name
     */
    country_name: string;
    /**
     * Scale Description
     */
    scale_description: string;
    /**
     * Total Grades
     */
    total_grades?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Equivalences
     */
    equivalences?: Array<GradeEquivalenceRead>;
};

/**
 * GradeEquivalenceCreate
 */
export type GradeEquivalenceCreate = {
    /**
     * Origin Grade
     *
     * Grade from origin country
     */
    origin_grade: string;
    /**
     * Spanish 5 10
     */
    spanish_5_10: number | string;
    /**
     * Spanish 1 4
     */
    spanish_1_4?: number | null;
    spanish_literal: SpanishLiteralEnum;
};

/**
 * GradeEquivalenceRead
 */
export type GradeEquivalenceRead = {
    /**
     * Origin Grade
     *
     * Grade from origin country
     */
    origin_grade: string;
    /**
     * Spanish 5 10
     */
    spanish_5_10: string;
    /**
     * Spanish 1 4
     */
    spanish_1_4?: number | null;
    spanish_literal: SpanishLiteralEnum;
    /**
     * Id
     */
    id: number;
    /**
     * Scale Id
     */
    scale_id: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SpanishLiteralEnum
 */
export type SpanishLiteralEnum = 'APROBADO' | 'NOTABLE' | 'SOBRESALIENTE' | 'MATRICULA';

/**
 * TransferRequest
 *
 * Schema for the Activepieces automation request
 */
export type TransferRequest = {
    /**
     * Scale Id
     */
    scale_id: number;
    /**
     * Origin Grade
     */
    origin_grade: string;
};

/**
 * TransferResponse
 *
 * The clean data sent back to the automation flow
 */
export type TransferResponse = {
    /**
     * Original
     */
    original: string;
    /**
     * Converted 5 10
     */
    converted_5_10: string;
    /**
     * Converted Literal
     */
    converted_literal: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadScalesScalesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/scales/';
};

export type ReadScalesScalesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadScalesScalesGetError = ReadScalesScalesGetErrors[keyof ReadScalesScalesGetErrors];

export type ReadScalesScalesGetResponses = {
    /**
     * Response Read Scales Scales  Get
     *
     * Successful Response
     */
    200: Array<AcademicScaleRead>;
};

export type ReadScalesScalesGetResponse = ReadScalesScalesGetResponses[keyof ReadScalesScalesGetResponses];

export type CreateScaleScalesPostData = {
    body: AcademicScaleCreate;
    path?: never;
    query?: never;
    url: '/scales/';
};

export type CreateScaleScalesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScaleScalesPostError = CreateScaleScalesPostErrors[keyof CreateScaleScalesPostErrors];

export type CreateScaleScalesPostResponses = {
    /**
     * Successful Response
     */
    200: AcademicScaleRead;
};

export type CreateScaleScalesPostResponse = CreateScaleScalesPostResponses[keyof CreateScaleScalesPostResponses];

export type ReadScaleScalesScaleIdGetData = {
    body?: never;
    path: {
        /**
         * Scale Id
         */
        scale_id: number;
    };
    query?: never;
    url: '/scales/{scale_id}';
};

export type ReadScaleScalesScaleIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadScaleScalesScaleIdGetError = ReadScaleScalesScaleIdGetErrors[keyof ReadScaleScalesScaleIdGetErrors];

export type ReadScaleScalesScaleIdGetResponses = {
    /**
     * Successful Response
     */
    200: AcademicScaleRead;
};

export type ReadScaleScalesScaleIdGetResponse = ReadScaleScalesScaleIdGetResponses[keyof ReadScaleScalesScaleIdGetResponses];

export type CreateEquivalenceForScaleScalesScaleIdEquivalencesPostData = {
    body: GradeEquivalenceCreate;
    path: {
        /**
         * Scale Id
         */
        scale_id: number;
    };
    query?: never;
    url: '/scales/{scale_id}/equivalences/';
};

export type CreateEquivalenceForScaleScalesScaleIdEquivalencesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEquivalenceForScaleScalesScaleIdEquivalencesPostError = CreateEquivalenceForScaleScalesScaleIdEquivalencesPostErrors[keyof CreateEquivalenceForScaleScalesScaleIdEquivalencesPostErrors];

export type CreateEquivalenceForScaleScalesScaleIdEquivalencesPostResponses = {
    /**
     * Successful Response
     */
    200: GradeEquivalenceRead;
};

export type CreateEquivalenceForScaleScalesScaleIdEquivalencesPostResponse = CreateEquivalenceForScaleScalesScaleIdEquivalencesPostResponses[keyof CreateEquivalenceForScaleScalesScaleIdEquivalencesPostResponses];

export type ConvertGradeTransferConvertPostData = {
    body: TransferRequest;
    path?: never;
    query?: never;
    url: '/transfer/convert';
};

export type ConvertGradeTransferConvertPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConvertGradeTransferConvertPostError = ConvertGradeTransferConvertPostErrors[keyof ConvertGradeTransferConvertPostErrors];

export type ConvertGradeTransferConvertPostResponses = {
    /**
     * Successful Response
     */
    200: TransferResponse;
};

export type ConvertGradeTransferConvertPostResponse = ConvertGradeTransferConvertPostResponses[keyof ConvertGradeTransferConvertPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
